### ISSUE TITLE
The email is being pasted as "Your Email" and browser keeps closing after Mobile search begins

### ISSUE THREAD

**Issue by jackjack21-pixel** [MehdiRtal/MicrosoftRewardsClaimer#10]
I am able to run the program but my email address is not being pasted into Microsoft Bing Rewards website. It is being pasted as "YOUR EMAIL" 

also, i have only edited the accounts.json file and i see "email.json.". I edited both. 

@dmarts05 
@MehdiRtal

**Comment by jackjack21-pixel** [comment]
To fix this issue, first, enable two factor authentication for outlook account if have any
- copy your email and as soon as you run your program and see this error, paste your email and write your password quickly. Don’t pres enter or next.
- That should fix the issue. Also, don’t close tab.

**Comment by jackjack21-pixel** [comment]
Here is the Pastebin for py file: https://pastebin.com/wThuMHCV

**Comment by jackjack21-pixel** [comment]
Here is the Pastebin for py file: https://pastebin.com/wThuMHCV

**Comment by jackjack21-pixel** [comment]
@MehdiRtal 
@dmarts05

**Comment by dmarts05** [comment]
Have you set up the accounts.json file and have you installed webdriver?

**Comment by jackjack21-pixel** [comment]
Yes, the issue might be this part of code

`with open("accounts.json", 'w') as f:
                f.write(json.dumps([{
                    "username": "Your Email",
                    "password": "Your Password"
                }], indent=4))
`

I removed this part because i don't need it and then i added this

`def loadAccounts():
    global ACCOUNTS
    if ARGS.accounts:
        ACCOUNTS = []
        for account in ARGS.accounts:
            ACCOUNTS.append({"username": account.split(":")[0], "password": account.split(":")[1]})
    else:
        try:
            ACCOUNTS = json.load(open("accounts.json", "r"))
        except FileNotFoundError:
            print("Please create an `accounts.json` file and try again.")
`

Sorry i forgot to close the issue
