### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'quit'

### ISSUE THREAD

**Issue by jackjack21-pixel** [MehdiRtal/MicrosoftRewardsClaimer#9]
Please help someone, I am getting this error
` line 1710, in farmer
    browser. Quit()
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'quit'`

Please help me out on this issue as i have no prior cding experience, if discord works better let me know as well. Thanks
@dmarts05 
@charlesbel
@Farshadz1997
@Prem-ium

**Comment by jackjack21-pixel** [comment]
@MehdiRtal

**Comment by dmarts05** [comment]
Have you installed Chrome / Chromedriver?

**Comment by jackjack21-pixel** [comment]
I have installed edge driver

**Comment by dmarts05** [comment]
We only provide support for Google Chrome Webdriver.

**Comment by jackjack21-pixel** [comment]
Oh so, should i just download chrome and chromewebsdriver? Or do i have to do any other modification?

**Comment by dmarts05** [comment]
Installing Google Chrome should do the trick.
